# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 8.x
    performMultiLevelLookup: true
    includePreviewVersions: true
- task: DotNetCoreCLI@2
  displayName: 'Restore Solution'
  inputs:
    command : "restore"

- task: DotNetCoreCLI@2
  displayName: 'Build Solution'
  inputs:
    command : "build"
    arguments: '--configuration $(buildConfiguration) --no-restore'
- task: DotNetCoreCLI@2
  displayName: 'Run UnitTests'
  inputs:
    command: 'test'
    arguments: '--no-build --verbosity normal --configuration $(buildConfiguration) --filter FullyQualifiedName!~IntegrationTests'
    publishTestResults: false
 